// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZM6XlmhQrTfz7-HV7-85nqi7W4qERV74',
    appId: '1:879054678488:web:d25762a9fd39b47a56eaad',
    messagingSenderId: '879054678488',
    projectId: 'bora-ai-62621',
    authDomain: 'bora-ai-62621.firebaseapp.com',
    storageBucket: 'bora-ai-62621.firebasestorage.app',
    measurementId: 'G-M2C8T0GEMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDorxjbx-Y-E-Qbol_1ooLu0OnzF-aMD_s',
    appId: '1:879054678488:android:679bbc501190e0cc56eaad',
    messagingSenderId: '879054678488',
    projectId: 'bora-ai-62621',
    storageBucket: 'bora-ai-62621.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIL5Id9LEN-2naT5a9NYQaTRo9aIecrQ0',
    appId: '1:879054678488:ios:f6af7a66939805bb56eaad',
    messagingSenderId: '879054678488',
    projectId: 'bora-ai-62621',
    storageBucket: 'bora-ai-62621.firebasestorage.app',
    androidClientId: '879054678488-vbjhvn2ke262hitc2cb3frg0u0tup7m3.apps.googleusercontent.com',
    iosClientId: '879054678488-mhkh29q1bi5821n5brc36lccv6ejnnba.apps.googleusercontent.com',
    iosBundleId: 'com.example.boraAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIL5Id9LEN-2naT5a9NYQaTRo9aIecrQ0',
    appId: '1:879054678488:ios:f6af7a66939805bb56eaad',
    messagingSenderId: '879054678488',
    projectId: 'bora-ai-62621',
    storageBucket: 'bora-ai-62621.firebasestorage.app',
    androidClientId: '879054678488-vbjhvn2ke262hitc2cb3frg0u0tup7m3.apps.googleusercontent.com',
    iosClientId: '879054678488-mhkh29q1bi5821n5brc36lccv6ejnnba.apps.googleusercontent.com',
    iosBundleId: 'com.example.boraAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZM6XlmhQrTfz7-HV7-85nqi7W4qERV74',
    appId: '1:879054678488:web:865ca043416f6f9f56eaad',
    messagingSenderId: '879054678488',
    projectId: 'bora-ai-62621',
    authDomain: 'bora-ai-62621.firebaseapp.com',
    storageBucket: 'bora-ai-62621.firebasestorage.app',
    measurementId: 'G-LM8YH9M8R3',
  );
}
